set encoding=utf-8

" Don't run in legacy mode
set nocompatible

" Install vim-plug if we don't already have it
if empty(glob("~/.vim/autoload/plug.vim"))
    execute '!curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    " Create plugins directory
    execute '!mkdir -p ~/.vim/plugins'
endif

" Include plugins
source $HOME/.vim/plugins.vim

" Basics
syntax on			    " Enable syntax highlighting
set nobackup            " don't make foo~ files
set autowrite 			" Save file before other commands like :next
set number
colorscheme luna
set background=dark
filetype plugin on
filetype plugin indent on

" Indentation
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smartindent
set smarttab
"" smart backspace with autoindent
set backspace=indent,eol,start

" Search
set rtp+=/opt/homebrew/bin/fzf
"" map space to clear search highlighting and close scratch windows
nnoremap <silent> <Space> :silent noh<Bar>:pc<Bar>echo<CR>
set hlsearch 			" Highlight search term
set incsearch			" Show search while typing
set ignorecase			" Case insensitive search
set smartcase			" Override ignorecase if search term has uppercase