#!/usr/bin/env bash

if [ $# -ne 2 ]; then
    echo "$0 - Creates a GIF from a video using ffmpeg and gifsicle"
    echo "Usage: $0 <input-filename> <output-filename>"
    exit 1
fi

which ffmpeg > /dev/null
if [ $? -ne 0 ]; then
    echo "ERROR: 'ffmpeg' not found. Exiting."
    exit 2
fi

which gifsicle > /dev/null
if [ $? -ne 0 ]; then
    echo "ERROR: 'gifsicle' not found. Exiting."
    exit 2
fi

infile="${1}"
outfile="${2}"

# Check if input file exists
if [ ! -f ${infile} ]; then
    echo "Input file - ${infile} - does not exist. Aborting..."
    exit
fi

# Check if output file exists
if [ -f ${outfile} ]; then
    echo "Output file - ${outfile} - already exists."
    echo "Please delete output file before proceeding. Aborting..."
    exit
fi

## Run the conversion
ffmpeg -i "${infile}" -pix_fmt rgb24 -r 5 -f gif - | gifsicle --optimize=3 > "${outfile}"
echo "Done with conversion."
