#!/usr/bin/env bash

IFS='
'
SRCDIR="$GOPATH/src"

NC='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
BROWN='\033[0;33m'

function git_status() {
    repo="$1"
    pushd ${repo} > /dev/null
    git fetch --all &> /dev/null
    branch=$(git symbolic-ref -q HEAD)
    if [ "$branch" == "refs/heads/master" ]; then
        localStatus=$(git diff --stat master)
        if [ ! -z "$localStatus" ]; then
            # We have local uncommitted changes
            echo "$RED"
        else
            status=$(git diff --stat origin/master)
            if [ -z "$status" ]; then
                # In Sync with remote master
                echo "$GREEN"
            else
                # Diverged from remote master
                echo $BROWN
            fi
        fi
    else
        # Local branch is not master
        echo $RED
    fi
    popd > /dev/null
}


for x in `tree -f -d -L 3 $SRCDIR`; do
    prefix=${x%$SRCDIR*}
    repo=${x##$prefix}
    base=$(basename $repo 2>/dev/null)
    printf "$prefix"
    if [ -d $repo/.git ]; then
        status=$(git_status $repo)
        printf "${status}$base${NC}\n"
    else
        printf "$base\n"
    fi
done
