#!/usr/bin/env bash

DOWNLOAD_DIR="$HOME/Downloads"
INSTALL_DIR="$HOME/apps"

command -v jq >/dev/null || { echo >&2 "jq is required but not found. Exiting"; exit 1; }
if [ ! -d "$DOWNLOAD_DIR" ]; then echo "$DOWNLOAD_DIR does not exist. Exiting"; exit 1; fi

OS=$(uname -s)
ARCH=$(uname -m)
VERSION="master"

if [ "$OS" == "Darwin" ]; then
	OS="macos"
fi

if [ "$ARCH" == "arm64" ]; then
	ARCH="aarch64"
fi

if [ -n "$1" ]; then
	VERSION="$1"
fi

PLATFORM="$ARCH-$OS"

URL=$(curl -s "https://ziglang.org/download/index.json" | jq -r ".\"$VERSION\".\"$PLATFORM\".tarball")
FILENAME="$DOWNLOAD_DIR/$(basename $URL)"
ZIG=$(basename "$URL" .tar.xz)

if [ ! -f "$FILENAME" ]; then
	echo "Downloading $URL to $FILENAME"
	curl -so "$FILENAME" "$URL"
else
	echo "Skipping download. $FILENAME already exists."
fi

echo "Installing to $INSTALL_DIR/$ZIG"
tar -xf "$FILENAME" -C "$INSTALL_DIR"

echo "Symlinking $INSTALL_DIR/$ZIG to $INSTALL_DIR/zig"
ln -sfn $INSTALL_DIR/$ZIG $INSTALL_DIR/zig

if [[ ":$PATH:" == *":$INSTALL_DIR/zig:"* ]]; then
	echo "\$PATH already set correctly"
else
	echo -e "\nPlease add \"export PATH=$INSTALL_DIR/zig:\$PATH\"to your bashrc"
fi

echo -e "\nDone.\n"



