#!/usr/bin/env bash

if [[ -z $1 ]]; then
    echo "Usage: mssh <session-name> [host]..."
    exit 0
fi

session=$1
shift
hosts=($@)

# Create session
# -d detach any other clients attached to the sessioin
# -s session name
tmux new-session -d -s $session 2> /dev/null

# Create window named ssh if it does not already exist
tmux if-shell 'tmux select-window -t ${session}:ssh' '' 'new-window -t ${session} -n ssh'

# Kill all panes except the first one
tmux kill-pane -a -t 0

# Split into len(hosts) panes
for (( i=0; i < ${#hosts[@]}-1; i++ )); do
    tmux split-window
    tmux select-layout even-horizontal
done

# Relayout to grid layout
tmux select-layout tiled

# SSH into the hosts
for (( i = 0; i < ${#hosts[@]}; i++ )); do
    tmux select-pane -t $i
    tmux send-keys "ssh ${hosts[$i]}" C-m
done

# Connect to the session
tmux attach-session -t $session

# Set all panes to receive keyboard input
tmux set synchronize-panes on
