# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export LC_ALL="en_US.UTF-8"
export PATH=$HOME/bin/commands:/opt/homebrew/bin:$PATH
type brew &>/dev/null && export FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM=$ZSH/custom

if [[ ! -d $ZSH_CUSTOM/plugins/zsh-syntax-highlighting ]]; then
	git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM}/plugins/zsh-syntax-highlighting
fi

if [[ ! -d $ZSH_CUSTOM/plugins/zsh-autosuggestions ]]; then
	git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM}/plugins/zsh-autosuggestions
fi

if [[ ! -d $ZSH_CUSTOM/themes/powerlevel10k ]]; then
	git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM}/themes/powerlevel10k
fi

ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(
	git
	colored-man-pages
	colorize
	brew
	macos
	docker
	zsh-autosuggestions
	zsh-syntax-highlighting
	direnv
)

[[ "$(uname)" == "Darwin" ]] && plugins+=(fzf gpg-agent)
[[ "$(uname)" == "Linux" ]] && plugins+=(dnf)
source $ZSH/oh-my-zsh.sh
source $HOME/bin/zsh/aliases
source $HOME/bin/zsh/exports
source $HOME/bin/zsh/python
source $HOME/bin/zsh/golang
source $HOME/.localbashrc

# Remote GPG forwarding
[[ "$(uname)" == "Linux" ]] && type gpgconf &>/dev/null && gpgconf --create-socketdir
[[ "$(uname)" == "Linux" ]] && type gpgconf &>/dev/null && export SSH_AUTH_SOCK=$(gpgconf --list-dir agent-ssh-socket)

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

## Enable mcfly if installed
type mcfly &>/dev/null && eval "$(mcfly init zsh)"

