#!/usr/bin/env bash

#-------------------------------------------------------------------------------
# Protect against accidents
#-------------------------------------------------------------------------------
alias rm='rm -I --preserve-root'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

#-------------------------------------------------------------------------------
# Directory creation and navigation
#-------------------------------------------------------------------------------
alias mkdir='mkdir -pv'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

#-------------------------------------------------------------------------------
# Directory listing
#-------------------------------------------------------------------------------
export LSCOLORS=GxFxCxDxBxegedabagaced
alias sl='ls'
alias l='ls'
alias ls='ls --color=auto'
alias ll='ls -lthr --color=auto'
alias la='ls -lthra --color=auto'

#-------------------------------------------------------------------------------
# Colorize
#-------------------------------------------------------------------------------
alias diff='colordiff'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

#-------------------------------------------------------------------------------
# Date and time
#-------------------------------------------------------------------------------
alias now='date'
alias isodate='date +"%Y-%m-%d"'
alias today='date +"%d/%m/%Y"'
alias td='vim +Note$(date +"%Y-%m-%d")'
alias yt='vim +Note$(date +"%Y-%m-%d" --date="1 day ago")'

#-------------------------------------------------------------------------------
# Sysadmin
#-------------------------------------------------------------------------------
alias top='htop'
alias free='free -g -l -t'
alias df='df -h'
alias du='du -h'
alias psmem='ps aux --sort -rss | head'
alias pscpu='ps aux --sort -pcpu | head'
alias path='echo -e ${PATH//:/\\n}'

#-------------------------------------------------------------------------------
# Programming
#-------------------------------------------------------------------------------
alias vi='vim'
alias emacs='emacs --no-window-system'
alias man='man -a'
alias t='tmux'
alias ta='tmux a'
alias typora='open -a typora'

#-------------------------------------------------------------------------------
# Git
#-------------------------------------------------------------------------------
alias amend='git commit --amend'
alias g='git status'
alias ga='git add'
alias gb='git branch -a'
alias gc='git commit'
alias gcb='git checkout -b'
alias gco-='git checkout --'
alias gco='git checkout'
alias gd='git diff'
alias gl='git log -10'
alias gls='git log --graph --oneline --decorate'
alias gpp='git pull --prune'
alias gpurge='git clean -fd'
alias push='git push'
__git_complete ga _git_add
__git_complete gb _git_branch
__git_complete gc _git_commit
__git_complete gco _git_checkout
__git_complete gco- _git_checkout
__git_complete gd _git_diff
__git_complete gl _git_log
__git_complete gls _git_log
__git_complete gpp _git_pull
__git_complete push _git_push

#-------------------------------------------------------------------------------
# Docker
#-------------------------------------------------------------------------------
alias d=docker
complete -F _docker d
alias dp='docker ps'
alias dpa='docker ps --all'
alias di='docker images'
alias drmi='docker images --quiet --filter=dangling=true | xargs --no-run-if-empty docker rmi'

#-------------------------------------------------------------------------------
# Kubernetes
#-------------------------------------------------------------------------------
alias k=kubectl
alias kgd='kubectl get deployments'
alias kgn='kubectl get namespaces'
alias kgp='kubectl get pods'
alias kgs='kubectl get services'
alias kn=kubens
alias kx=kubectx
complete -F __kubectl_get_resource_pod kgp
complete -F __start_kubectl k
complete -F _kube_contexts kx
complete -F _kube_namespaces kn
