#!/usr/bin/env bash

#-------------------------------------------------------------------------------
# Protect against accidents
#-------------------------------------------------------------------------------
alias rm='rm -I --preserve-root'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

#-------------------------------------------------------------------------------
# Directory creation and navigation
#-------------------------------------------------------------------------------
alias mkdir='mkdir -pv'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

#-------------------------------------------------------------------------------
# Directory listing
#-------------------------------------------------------------------------------
export LSCOLORS=GxFxCxDxBxegedabagaced
alias sl='ls'
alias l='ls'
alias ls='ls --color=auto'
alias ll='ls -lthr --color=auto'
alias la='ls -lthra --color=auto'

#-------------------------------------------------------------------------------
# Colorize
#-------------------------------------------------------------------------------
alias diff='colordiff'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

#-------------------------------------------------------------------------------
# Date and time
#-------------------------------------------------------------------------------
alias now='date'
alias isodate='date +"%Y-%m-%d"'
alias today='date +"%d/%m/%Y"'
alias td='vim +Note$(date +"%Y-%m-%d")'
alias yt='vim +Note$(date +"%Y-%m-%d" --date="1 day ago")'

#-------------------------------------------------------------------------------
# Sysadmin
#-------------------------------------------------------------------------------
alias top='htop'
alias free='free -g -l -t'
alias df='df -h'
alias du='du -h'
alias psmem='ps aux --sort -rss | head'
alias pscpu='ps aux --sort -pcpu | head'
alias path='echo -e ${PATH//:/\\n}'

#-------------------------------------------------------------------------------
# Programming
#-------------------------------------------------------------------------------
alias vi='vim'
alias emacs='emacs --no-window-system'
alias man='man -a'
alias t='tmux'
alias ta='tmux a'
alias typora='open -a typora'

#-------------------------------------------------------------------------------
# Git
#-------------------------------------------------------------------------------
alias g='git status'
alias gd='git diff'
alias gpp='git pull --prune'

#-------------------------------------------------------------------------------
# Docker
#-------------------------------------------------------------------------------
alias d=docker
complete -F _docker d
alias dp='docker ps'
alias dpa='docker ps --all'
alias di='docker images'
alias drmi='docker images --quiet --filter=dangling=true | xargs --no-run-if-empty docker rmi'

#-------------------------------------------------------------------------------
# Kubernetes
#-------------------------------------------------------------------------------
alias k=kubectl
alias kgd='kubectl get deployments'
alias kgn='kubectl get namespaces'
alias kgp='kubectl get pods'
alias kgs='kubectl get services'
alias kn=kubens
alias kx=kubectx
complete -F __kubectl_get_resource_pod kgp
complete -F __start_kubectl k
complete -F _kube_contexts kx
complete -F _kube_namespaces kn

function _kxn() {
    fields=(${@//\// })
    kx ${fields[0]}
    kn ${fields[1]}
}
alias kxn=_kxn
