#!/usr/bin/env bash

#-------------------------------------------------------------------------------
# Protect against accidents
#-------------------------------------------------------------------------------
alias rm='rm -I --preserve-root'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

#-------------------------------------------------------------------------------
# Directory creation and navigation
#-------------------------------------------------------------------------------
alias mkdir='mkdir -pv'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

#-------------------------------------------------------------------------------
# Colorize
#-------------------------------------------------------------------------------
alias diff='colordiff'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

#-------------------------------------------------------------------------------
# Sysadmin
#-------------------------------------------------------------------------------
alias top='htop'
alias free='free -g -l -t'
alias df='df -h'
alias du='du -h'
alias psmem='ps aux --sort -rss | head'
alias pscpu='ps aux --sort -pcpu | head'
alias path='echo -e ${PATH//:/\\n}'

#-------------------------------------------------------------------------------
# Programming
#-------------------------------------------------------------------------------
alias vi='vim'
alias man='man -a'
alias t='tmux'
alias ta='tmux a'

#-------------------------------------------------------------------------------
# Git
#-------------------------------------------------------------------------------
alias g='git status'
alias gpp='git pull --prune'

#-------------------------------------------------------------------------------
# Utilities
#-------------------------------------------------------------------------------
function lcd() {
    which bfind &> /dev/null || exit
    d=$(bfind -type d -1 -name "$@" $(pwd))
    if [ -n "$d" ]; then
        cd "$d"
    fi
}
