#.bashrc

# Bash Configuration v1.2
#
# Create Date: 2017-07-30
#
# Modified Dates:
#   v1.1    : 2017-08-25. Various bugfixes.
#   v1.2    : 2017-08-26. Disable load on non interactive sessions
#

# Don't load this file if this is not an interactive session
[ -z "$PS1" ] && return

#-------------------------------------------------------------------------------
# PATH
#-------------------------------------------------------------------------------
export PATH=/usr/local/bin:$PATH
export PATH=$HOME/bin/commands:$PATH
export PATH=/usr/local/texlive/2018/bin/x86_64-darwin:$PATH
export PATH=/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/make/libexec/gnubin:$PATH
export MANPATH=/usr/local/opt/coreutils/libexec/gnuman:/usr/local/opt/make/libexec/gnuman:$MANPATH

#-------------------------------------------------------------------------------
# Shell options
#-------------------------------------------------------------------------------
# Enable autocomplete
set autolist
# Disable terminal audio-visual bell
set bell-style none
# Store multi-line commands in a single history entry
shopt -s cmdhist
# Enable extended pattern matching operators
shopt -s extglob
# Apped history to existing files instead of overwriting
shopt -s histappend
# Case-insensitive globbing
shopt -s nocaseglob
# Autocorrect typos in path names when using `cd`
shopt -s cdspell
# Enable programmable completion
shopt -s progcomp

#-------------------------------------------------------------------------------
# Basics
#-------------------------------------------------------------------------------
files="/etc/bashrc $HOME/bin/bash/exports $HOME/bin/bash/aliases
$HOME/bin/bash/gpg-ssh $HOME/bin/bash/golang
/usr/local/etc/bash_completion"

for file in $files; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file"
done
# Only load bash completions if it is an interactive session
if [ ! -z "$PS1" ]; then
    for f in ~/bin/bash/completions/*; do
        source "$f"
    done
fi
unset files
unset file
unset f

#-------------------------------------------------------------------------------
# Prompt
#-------------------------------------------------------------------------------
if [ "$(whoami)" == "root" ]; then
    # Root's prompt (bold red)
    export PS1='\[\e[1;31m\][\u@\h \w]\$\[\e[0m\] '
else
    # Normal user's prompt (bold green)
    export PS1='\[\e[1;32m\][\u@\h \w]\$\[\e[0m\] '
fi
# Terminal window title
export PROMPT_COMMAND='echo -ne "\033]0;${PWD#$HOME\/}\007"'

#-------------------------------------------------------------------------------
# Local configuration
#-------------------------------------------------------------------------------
if [ -f ~/.localbashrc ] && \
	([ $0 == "-bash" ] || [ $(basename $0) == "bash" ]); then
    . $HOME/.localbashrc
fi
