#!/usr/bin/env bash

#-------------------------------------------------------------------------------
# Golang configuration
#-------------------------------------------------------------------------------
# Function to easily jump to anywhere in the GOPATH
function _godir() {
    basedir="$HOME/go/src"
    # If not argument is provided, go the $basedir
    # Otherwise, use the argument as a regex to jump to the first matching path
    if [ -z $1 ]; then
	    pushd "${basedir}"
    else
        if which bfind &> /dev/null; then
            newdir=$(bfind -type d -name ".*${1}.*" -1 "$basedir")
        else
            newdir=$(find "$basedir" -type d -path "*${1}*" -print -quit)
        fi
        pushd "${newdir}"
    fi
}

# Function to `git clone` to GOPATH from URLs copied from browser
function _ggc() {
    imports=($@)
    for i in "${imports[@]}"; do
        i=${i#http*://}
        i=${i#git*://}
        repo=$HOME/go/src/$i
        if [ -d $repo ]; then
            pushd $repo
            git pull --prune
            popd
            continue
        fi
        parent=$(dirname $repo)
        mkdir -p $parent
        pushd $parent
        echo "Cloning https://$i"
        git clone https://$i $(basename $i)
        popd
    done
}

# Function to `go get` from URLs copied from browser
function _gg() {
    imports=($@)
    for i in "${imports[@]}"; do
        i=${i#http*://}
        i=${i#git*://}
        go get $i
    done
}

#-------------------------------------------------------------------------------
# Golang aliases
#-------------------------------------------------------------------------------
alias gg=_gg
alias ggc=_ggc
alias godir=_godir
alias gocover="go test -v -coverprofile=c.out && go tool cover -html=c.out"
alias gt='go test -v -race -cover -bench ./...'
